### ISSUE TITLE
ModuleNotFoundError: No module named 'mmhuman3d.data'

### ISSUE THREAD

**Issue by codeHorasan** [open-mmlab/mmhuman3d#209]
Does anyone know how to handle this issue?

**Comment by caizhongang** [comment]
```text
mmhuman3d/ <- the outer folder
└── mmhuman3d/ <- the mmhuman3d module
        └── data/
```

It seems that you take MMHuman3D as a submodule without installing it. Hence, when importing from mmhuman3d, the Python import system takes the outer mmhuman3d folder as the module entrance instead of mmhuman3d/mmhuman3d. 

If this is the case, remove the `__init__.py` in mmhuman3d/ (the outer folder), and within the outer folder run `pip install -e .` should address your issue.
