### ISSUE TITLE
How to get the intrinsics and extrinsics of the demo output?

### ISSUE THREAD

**Issue by Miles629** [open-mmlab/mmhuman3d#276]
Thank you for your great work! I run the single-person demo according to [page](https://mmhuman3d.readthedocs.io/en/latest/getting_started.html), and I tried hmr and vibe. the outputs are the same format.
just like the following:
```
['__key_strict__', '__data_len__', '__keypoints_compressed__', 'smpl',
 'verts', 'pred_cams', 'bboxes_xyxy', 'image_path', 'person_id', 'frame_id']
```
I got the ouput which is correctly visualization, but  I have some (maybe simple) questions:
 The input images are not square but rectangle, but the outputs pred_cams is of `(frames_num,3)` stand for `s,tx,ty` for each image. I guess the pred_cams is 'weak perspective camera parameters in cropped image space (s,tx,ty)' , but I don't know how to  get the cropped images.  By using the pred_cams (s,tx,ty) to calculate the  extrinsics of original images seems not good.
 So I wander to know how to get cropped images? and how to get cams of (sx,sy,tx,ty)?

**Comment by ttxskk** [comment]
Hi @Miles629,

Thanks for your interest.

A1:
In our demo, we first use MMDet to detect human BBox from the input image. After that, given the original image and the detected BBox, the data pipeline applies an [affine transformation](https://github.com/open-mmlab/mmhuman3d/blob/main/mmhuman3d/data/datasets/pipelines/transforms.py#L756)  to the original image, and the cropped image appears to have been stored in the [result list](https://github.com/open-mmlab/mmhuman3d/blob/main/mmhuman3d/data/datasets/pipelines/transforms.py#L771). However, our [inference pipeline](https://github.com/open-mmlab/mmhuman3d/blob/main/mmhuman3d/apis/inference.py#L194-L200) does not return cropped images, but recently, community user @Zessay created a PR #274  to resolve this issue. Would you mind merging this PR and checking it?  Looking forward to your feedback.

A2: 
You can refer to [visualize_smpl_vibe](https://github.com/open-mmlab/mmhuman3d/blob/main/mmhuman3d/core/visualization/visualize_smpl.py#L1123) which calls [convert_crop_cam_to_orig_img](https://github.com/open-mmlab/mmhuman3d/blob/1dd2d281a775a2da197074ace698be324f3f8196/mmhuman3d/utils/demo_utils.py#L99).

**Comment by ttxskk** [comment]
Hi @Miles629, I seem to be confusing the data augmentation results with the output of the model. The data augmentation results are stored in this [dict](https://github.com/open-mmlab/mmhuman3d/blob/main/mmhuman3d/apis/inference.py#L174).

**Comment by Miles629** [comment]
Thank you for your answer! It really helps me a lot! Good luck!

**Comment by Miles629** [comment]
Thank you for your reply! Now, I successfully get the origin cams by
```
img_h,img_w = img.shape[:-1]
orig_cams = convert_crop_cam_to_orig_img(pred_cams,bboxs,img_w,img_h,aspect_ratio=1.0,bbox_scale_factor=1.25,bbox_format='xyxy')
```
Following the [tutorial](https://mmhuman3d.readthedocs.io/en/latest/cameras.html), `WeakPerspectiveCameras.convert_orig_cam_to_matrix` can transform the orig_cams to intrinsics matrix of Pytorch3d coordinate(top of the tutorial writes 'We follow Pytorch3D cameras.' ), like this:
`K, R, T = WeakPerspectiveCameras.convert_orig_cam_to_matrix(torch.tensor(orig_cams))`
but I found the method(convert_orig_cam_to_matrix) note this:
 ```
Returns:
            Tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
            opencv intrinsic matrix: (N, 4, 4)
```
I want to make sure that the returned K is on pytorch3d cameras or opencv cameras?  And usually I think R, T are part of extrinsics, but I'm not sure here. 

If I want to get the intrinsics and extrinsics (opencv format) of my data, can I run the following code to get the final result?
intrinsics : `K = convert_K_4x4_to_3x3(K, is_perspective=True)`
extrinsics : 
[RT
01]

BTW, My ultimate goal is to obtain these data following, and I believe mmhuman3d can do. I'm sorry that I have so many problems that take up your time. Thank you again for your efforts.

- human body pose (SMPL poses and betas coefficients)
- camera pose (camera intrinsic and extrinsic matrices), which follow [OpenCV](https://learnopencv.com/geometry-of-image-formation/) camera coordinate system and use [pinhole camera model](https://staff.fnwi.uva.nl/r.vandenboomgaard/IPCV20162017/LectureNotes/CV/PinholeCamera/PinholeCamera.html).

**Comment by SiriusNEO** [comment]
Hello @Miles629, I'm doing similar things like you. About the camera, I find it really helpful to follow the function `visualize_smpl_vibe` which calls `render_smpl` in `core/visualization/visualize_smpl/py`. The total process (pred_cams->orig_cams->intrinsics and extrinsics) can be figured out by reading the code.

About the convention, it can be found in line 992 of this file that `convention_src` is opencv and `convention_dst` is pytorch3d.

BTW, I am also confused with the note of `convert_orig_cam_to_matrix` because it indeed returns `K, R, T` instead of just `K`.

**Comment by ttxskk** [comment]
Hi, @Miles629,

A1:
First, the convention of the predicted camera is `OpenCV`(In this [line](https://github.com/open-mmlab/mmhuman3d/blob/b9d88169c24d1d11d5c70dcd5e8b54dc574431b8/mmhuman3d/core/visualization/visualize_smpl.py#L1144), the convention is set to `OpenCV`) and we use [these lines](https://github.com/open-mmlab/mmhuman3d/blob/b9d88169c24d1d11d5c70dcd5e8b54dc574431b8/mmhuman3d/core/visualization/visualize_smpl.py#L897-L916) to specifically handle this case.

After that, we convert the `pred_cam`  to `K, R, T` in the OpenCV convention, but we have to convert the camera from the OpenCV convention to the PyTorch3D convention ([those lines](https://github.com/open-mmlab/mmhuman3d/blob/b9d88169c24d1d11d5c70dcd5e8b54dc574431b8/mmhuman3d/core/visualization/visualize_smpl.py#L991-L1000)) because the renderer is based on PyTorch3D.  

As for why the tutorial wrote that we follow the Pytorch3D camera, I guess it is because all the cameras defined in MMHuman3D, such as PerspectiveCameras, are inherited from PyTorch3D.

A2:
It looks like you can do this, but I'm not quite sure. You can check for yourself. (I think @JasonBoy1 can help you.)


BTW, I think you can achieve your goal as follows:
```python
# get trans
trans = np.concatenate([
    pred_cam[..., [1]], pred_cam[..., [2]], 2 * 5000. / 
    (224 * pred_cam[..., [0]] + 1e-9)
], -1)

# add trans to the mesh 
body_model = build_body_model(...)
verts = body_model(pose,shape,...)
verts = verts + trans
# render or some other operations
R = identity_matrix
T = ZERO
f = 5000. 
tx = ty = img_size/2 # image size =(224,224)

```
You can refer to #262 for details on how to build a mannequin and get translations.

**Comment by ttxskk** [comment]
Hi, @Miles629,

A1:
First, the convention of the predicted camera is OpenCV(In this [line](https://github.com/open-mmlab/mmhuman3d/blob/b9d88169c24d1d11d5c70dcd5e8b54dc574431b8/mmhuman3d/core/visualization/visualize_smpl.py#L1144), the convention is set to OpenCV) and we use [these lines](https://github.com/open-mmlab/mmhuman3d/blob/b9d88169c24d1d11d5c70dcd5e8b54dc574431b8/mmhuman3d/core/visualization/visualize_smpl.py#L897-L916) to specifically handle this case. After that, we have converted the pred_cam to K, R, T in the OpenCV convention, but we have to convert the camera from the OpenCV convention to the PyTorch3D convention ([those lines](https://github.com/open-mmlab/mmhuman3d/blob/b9d88169c24d1d11d5c70dcd5e8b54dc574431b8/mmhuman3d/core/visualization/visualize_smpl.py#L991-L1000)) because the renderer is based on PyTorch3D.

As for why the tutorial wrote that we follow the Pytorch3D camera, I guess it is because all the cameras defined in MMHuman3D, such as PerspectiveCameras, are inherited from PyTorch3D.

A2:
It looks like you can do this, but I'm not quite sure. You can check for yourself. (I think @JasonBoy1 can help you.)

BTW, I think you can achieve your goal as follows:

```python
# get trans
trans = np.concatenate([
    pred_cam[..., [1]], pred_cam[..., [2]], 2 * 5000. / 
    (224 * pred_cam[..., [0]] + 1e-9)
], -1)

# add trans to the mesh 
body_model = build_body_model(...)
verts = body_model(pose,shape,...)
verts = verts + trans
# render or some other operations
R = identity_matrix
T = ZERO
f = 5000. 
tx = ty = img_size/2 # image size =(224,224)
```
You can refer to https://github.com/open-mmlab/mmhuman3d/issues/262 for details on how to build a mannequin and get translations.

**Comment by ttxskk** [comment]
> Hello @Miles629, I'm doing similar things like you. About the camera, I find it really helpful to follow the function `visualize_smpl_vibe` which calls `render_smpl` in `core/visualization/visualize_smpl.py`. The total process (pred_cams->orig_cams->intrinsics and extrinsics) can be figured out by reading the code.
> 
> About the convention, it can be found in line 992 of this file that `convention_src` is opencv and `convention_dst` is pytorch3d.
> 
> BTW, I am also confused with the note of `convert_orig_cam_to_matrix` because it indeed returns `K, R, T` instead of just `K`.

Because in this case (camera is predicted) the R is the identity matrix, and T is ZERO vector.

**Comment by ttxskk** [comment]
Hi, @Miles629,

A1:
First, the convention of the predicted camera is OpenCV(In this [line](https://github.com/open-mmlab/mmhuman3d/blob/b9d88169c24d1d11d5c70dcd5e8b54dc574431b8/mmhuman3d/core/visualization/visualize_smpl.py#L1144), the convention is set to OpenCV) and we use [these lines](https://github.com/open-mmlab/mmhuman3d/blob/b9d88169c24d1d11d5c70dcd5e8b54dc574431b8/mmhuman3d/core/visualization/visualize_smpl.py#L897-L916) to specifically handle this case. After that, we have converted the pred_cam to K, R, T in the OpenCV convention, but we have to convert the camera from the OpenCV convention to the PyTorch3D convention ([those lines](https://github.com/open-mmlab/mmhuman3d/blob/b9d88169c24d1d11d5c70dcd5e8b54dc574431b8/mmhuman3d/core/visualization/visualize_smpl.py#L991-L1000)) because the renderer is based on PyTorch3D.

As for why the tutorial wrote that we follow the Pytorch3D camera, I guess it is because all the cameras defined in MMHuman3D, such as PerspectiveCameras, are inherited from PyTorch3D.

A2:
It looks like you can do this, but I'm not quite sure. You can check for yourself. (I think @JasonBoy1 can help you.)

BTW, I think you can achieve your goal as follows:

```python
# get trans
trans = np.concatenate([
    pred_cam[..., [1]], pred_cam[..., [2]], 2 * 5000. / 
    (224 * pred_cam[..., [0]] + 1e-9)
], -1)

# add trans to the mesh 
body_model = build_body_model(...)
verts = body_model(pose,shape,...)
verts = verts + trans
# render or some other operations
R = identity_matrix
T = ZERO
f = 5000. 
tx = ty = img_size/2 # image size =(224,224)
```
You can refer to https://github.com/open-mmlab/mmhuman3d/issues/262 for details on how to build a body model and get trans.

**Comment by ttxskk** [comment]
Hi, @Miles629,

A1:
Actually, it depends on the `convention` you assign to WeakPerspectiveCameras, but since `convert_orig_cam_to_matrix` is designed for the predicted camera whose convention is [OpenCV](https://github.com/open-mmlab/mmhuman3d/blob/b9d88169c24d1d11d5c70dcd5e8b54dc574431b8/mmhuman3d/core/visualization/visualize_smpl.py#L1144), the docstring describes like this.

A2:
From this [unit test](https://github.com/open-mmlab/mmhuman3d/blob/b9d88169c24d1d11d5c70dcd5e8b54dc574431b8/tests/test_cameras/test_camera_converter.py#L153-L158), I guess you can do this.

BTW, I think you also can achieve your goal as follows:
```
# get trans
trans = np.concatenate([
    pred_cam[..., [1]], pred_cam[..., [2]], 2 * 5000. / 
    (224 * pred_cam[..., [0]] + 1e-9)
], -1)

# add trans to the mesh 
body_model = build_body_model(...)
verts = body_model(pose,shape,...)
verts = verts + trans
# render or some other operations
R = identity_matrix
T = ZERO
f = 5000. 
tx = ty = img_size/2 # image size =(224,224)
```
You can refer to https://github.com/open-mmlab/mmhuman3d/issues/262 for details on how to build a body model and get trans.

**Comment by ttxskk** [comment]
> Hello @Miles629, I'm doing similar things like you. About the camera, I find it really helpful to follow the function `visualize_smpl_vibe` which calls `render_smpl` in `core/visualization/visualize_smpl.py`. The total process (pred_cams->orig_cams->intrinsics and extrinsics) can be figured out by reading the code.
> 
> About the convention, it can be found in line 992 of this file that `convention_src` is opencv and `convention_dst` is pytorch3d.
> 
> BTW, I am also confused with the note of `convert_orig_cam_to_matrix` because it indeed returns `K, R, T` instead of just `K`.

Thanks for pointing out this error. It looks like the description of R and T is missing here.

**Comment by Miles629** [comment]
Thank you @ttxskk ,thank you @SiriusNEO . Thank you for your very detailed reply and guidance, which helped me better understand these codes. Wish you happy life!
